
name: SuperKart MLOps Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  mlops:

    runs-on: ubuntu-latest

    steps:

      # --------------------------------
      # 1. Checkout repository
      # --------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4


      # --------------------------------
      # 2. Setup Python
      # --------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # --------------------------------
      # 3. Install dependencies
      # --------------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # --------------------------------
      # 4. Data preparation
      # --------------------------------

      - name: Prepare data
        run: |
          python src/data_prep.py


      # --------------------------------
      # 5. Train model
      # --------------------------------

      - name: Train and evaluate model
        run: |
          python src/train.py


      # --------------------------------
      # 6. Register model
      # --------------------------------

      - name: Register model with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          python src/register_model.py
